name: Playwright Tests
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ test, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.yarn
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: npm install -g yarn && yarn

    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps

    - name: Create user and admin json
      run: |
        mkdir -p playwright/.auth
        echo '{}' > playwright/.auth/user.json
        echo '{}' > playwright/.auth/tester01.json

    - name: Run Playwright tests
      run: yarn playwright test

    - name: Upload Playwright Report if Failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
